// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOZAoWfQs0NgJWelWB3KewJhIyq6KivOc',
    appId: '1:223042277147:web:02b98f2228325dcfcc8dbe',
    messagingSenderId: '223042277147',
    projectId: 'w4slinder',
    authDomain: 'w4slinder.firebaseapp.com',
    storageBucket: 'w4slinder.firebasestorage.app',
    measurementId: 'G-Q188BFXFBF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZayyBv3wn2DR74K1yND52nc8bRPnBAl4',
    appId: '1:223042277147:android:0e4f6f0e1496d3e9cc8dbe',
    messagingSenderId: '223042277147',
    projectId: 'w4slinder',
    storageBucket: 'w4slinder.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBxEz5m0awkVtR7Dt2tbjFA5WdAYdUvlA',
    appId: '1:223042277147:ios:047a8ecb3e41e174cc8dbe',
    messagingSenderId: '223042277147',
    projectId: 'w4slinder',
    storageBucket: 'w4slinder.firebasestorage.app',
    iosBundleId: 'com.washslender.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBxEz5m0awkVtR7Dt2tbjFA5WdAYdUvlA',
    appId: '1:223042277147:ios:32555845ca509567cc8dbe',
    messagingSenderId: '223042277147',
    projectId: 'w4slinder',
    storageBucket: 'w4slinder.firebasestorage.app',
    iosBundleId: 'com.example.carsMarket',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOZAoWfQs0NgJWelWB3KewJhIyq6KivOc',
    appId: '1:223042277147:web:3265c722bea62377cc8dbe',
    messagingSenderId: '223042277147',
    projectId: 'w4slinder',
    authDomain: 'w4slinder.firebaseapp.com',
    storageBucket: 'w4slinder.firebasestorage.app',
    measurementId: 'G-JV8M4FNQR8',
  );
}
