#!/usr/bin/env bash
# Creates a Play upload keystore + android/key.properties so release AABs are not debug-signed.
# Run from repo root: ./scripts/create_play_store_keystore.sh
# Backup upload-keystore.jks and passwords in a safe place — Google cannot recover a lost keystore.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
KEYSTORE_PATH="${KEYSTORE_PATH:-$ROOT/android/app/upload-keystore.jks}"
ALIAS="${KEY_ALIAS:-upload}"

if ! command -v keytool &>/dev/null; then
  echo "keytool not found. Install a JDK (e.g. Android Studio’s embedded JDK) and add it to PATH."
  exit 1
fi

if [[ -f "$KEYSTORE_PATH" ]]; then
  echo "Already exists: $KEYSTORE_PATH"
  echo "Delete it first if you want a new keystore, or set KEYSTORE_PATH to another file."
  exit 1
fi

if [[ -f "$ROOT/android/key.properties" ]]; then
  echo "Already exists: $ROOT/android/key.properties"
  echo "Remove or rename it first, or edit it manually to point at your keystore."
  exit 1
fi

echo "Play upload keystore will be created at:"
echo "  $KEYSTORE_PATH"
echo "Alias: $ALIAS"
echo ""
echo "You will be asked for:"
echo "  - Keystore password (store) and key password (can be the same)"
echo "  - Your name / org (for certificate — only used inside the keystore metadata)"
echo ""

# PKCS12 is the modern default; Play accepts it the same as JKS.
keytool -genkeypair -v \
  -keystore "$KEYSTORE_PATH" \
  -keyalg RSA -keysize 2048 -validity 10000 \
  -alias "$ALIAS" \
  -storetype PKCS12

echo ""
read -r -s -p "Keystore password (storePassword) again for key.properties: " STORE_PW
echo ""
read -r -s -p "Key password (keyPassword; press Enter if same as keystore): " KEY_PW
echo ""
if [[ -z "${KEY_PW}" ]]; then
  KEY_PW="$STORE_PW"
fi

# storeFile is relative to android/app (see android/app/build.gradle.kts)
REL_FILE="$(basename "$KEYSTORE_PATH")"
{
  echo "# Generated by scripts/create_play_store_keystore.sh — do not commit (gitignored)"
  echo "storePassword=$STORE_PW"
  echo "keyPassword=$KEY_PW"
  echo "keyAlias=$ALIAS"
  echo "storeFile=$REL_FILE"
} > "$ROOT/android/key.properties"
chmod 600 "$ROOT/android/key.properties"

echo ""
echo "Wrote: $ROOT/android/key.properties (mode 600)"
echo ""
echo "Next:"
echo "  1. Back up: $KEYSTORE_PATH and your passwords (password manager / secure storage)."
echo "  2. Build:   ./scripts/build_play_store_bundle.sh"
echo "  3. Upload:  build/app/outputs/bundle/release/app-release.aab to Play Console"
echo ""
